// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task4.Models;

#nullable disable

namespace Task4.Migrations
{
    [DbContext(typeof(ProductsContext))]
    partial class ProductsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Task4.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Яблоко",
                            Price = 49.0,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Name = "Вода",
                            Price = 69.0,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 3,
                            Name = "Лопата",
                            Price = 599.0,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 4,
                            Name = "Кактус",
                            Price = 259.0,
                            Quantity = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
